// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtvxneaveskidxjmfmiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0dnhuZWF2ZXNraWR4am1mbWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTg1NjMsImV4cCI6MjA3MjQzNDU2M30.90UuaNWPBjc07Ay5YnbDupoxBhaGWjvm1EdRap9hZwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});